[package]
name = "plsa-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = "0.6.2"
humantime = "2.1.0"
log = "0.4.20"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
thiserror = "1.0.53"

